export const ICON_MAP = {
  budget: "💰",
  guide: "👨‍🏫",
  hotel: "🏨",
  transport: "🚗",
  flight: "✈️",
  train: "🚆",
  food: "🍽",
  culture: "🎨",
  history: "🏛",
  nature: "🏔",
  trust: "🛡",
  match: "🎯",
  verified: "🪪",
  qualification: "🎓",
  star: "⭐",
  time: "⏱",
  safety: "🛡",
  eco: "🌿",
  city: "🏙",
  directory: "📚",
  experience: "🧭",
  reviews: "💬",
  reliability: "⏱",
  badge: "✨",
} as const;
